### ISSUE TITLE
Do you have a version with the ores and stuff already edited out?

### ISSUE THREAD

**Issue by blingblingdeveloper** [Campionnn/CleanCH#1]

**Comment by Campionnn** [comment]
I have not and am not planning on it as it would require many different versions which would become annoying to maintain. 

However, I am working on a mod that will easily allow people to create/edit routes along with the ability to toggle rendering of certain blocks in the world (stop them from showing). It is currently very WIP, but you can see it here https://github.com/Campionnn/Hollower. There is no documentation or pre-built mod yet so you would require some modding knowledge to compile one, but I would not recommend it as there's currently no way to get your routes in text form. Right now it's able to create/edit routes, and toggle rendering of blocks. Once college finals are over I will continue working on it

Here is a short video demonstrating what it can do so far

https://github.com/Campionnn/CleanCH/assets/19831081/2ec06088-cc2a-46f2-b6a6-acbfa5e03b15
